mcode/medmorph-backend

- .gitignore
- README.md
- package-lock.json
- package.json
- src/app.js
- src/routes/servers.js
- src/storage/DataAccess.js
- src/storage/__tests__/DataAccess.test.js
- src/storage/impl/Internal.js
- src/storage/impl/__tests__/Internal.test.js
Adds a "persistence layer" to the app, with an initial implementation of an in-memory DB with LokiJS. 
https://github.com/techfort/LokiJS
The starting API is very simple and inspired by SQL concepts:
- `select(collection, whereFn)`
- `insert(collection, value)`
- `update(collection, whereFn, updateFn)`
- `delete(collection, whereFn)`
By default, running the app in dev or production mode will persist the db to a file `medmorph.db`, autosaving every 5 seconds and loading at startup. In test mode, it will be in-memory only.
I also added the `/servers/` endpoint to exercise the database. It supports simple CRUD. (I chose "servers" on the assumption we'll probably need a "servers" collection for persisting auth credentials, see MEDMORPH-27. I don't think we'll need this API to be anything …
> Persistence Layer

- src/app.js
- src/routes/subscriptions.js
This adds a subscription endpoint at `/notif`.  You can test this by setting up the medmorph-ehr, posting the following subscription resource, posting any patient resource, and then modifying that patient resource with a PUT.
```{
"resourceType": "Subscription",
"id": "1",
"status": "active",
"criteria": "Patient?_id=1",
"channel": {
"type": "rest-hook",
"endpoint": "http://**your-ip-here**:3000/notif/1234",
"payload": "application/fhir+json"
}
}
```
To run this locally, if you're using docker, the medmorph-ehr will fail to find the locally ran version of the backend, so I referred to it by IP in testing.
This method will make a PUT request to the backend with the body populated with the fhir resource named in the criteria. If the `payload` parameter is replaced with `header` (or removed) …
> accept subscriptions

- src/utils/__tests__/fhir.test.js
- src/utils/fhir.js
Util functions to convert a KA Bundle or a single PlanDefinition into the necessary Subscriptions. This uses the R5 Backport for Subscriptions. Since `SubscriptionTopic`s don't exist in R4 the topic is defined via the canonical url and then it is up to the implementing server to know what those map to.
> Turn KnowldegeArtifacts into Subscriptions

- src/routes/index.js
Adding the `/jwks` endpoint to host the public keys. When registering this server as a client this is the endpoint used for the jwks-url.
Updated the Endpoint wiki with the new endpoint: https://github.com/mcode/medmorph-backend/wiki/Endpoints
> Add GET /jwks for Public JWKS

- src/app.js
- src/routes/public.js
Quick fix to make the JWKs url not require backend auth. Created a new /public route for endpoints which don't require authorization
> Make jwks url public

- src/utils/__tests__/reporting_workflow.test.js
- src/utils/reporting_workflow.js
PlanDefinitions in the MedMorph IG allow for timed offsets between actions, using the `PlanDefinition.action.relatedAction.offsetDuration` field.
This PR adds support for these timed offsets, by treating an offset as a new entry in the action sequence that causes a break out of the main loop, and calls setTimeout with the context pointing to the next action. It's admittedly very hackish but I feel like any more elegant solution will be a lot longer. I'm open to suggestions.
Note that this does not add a job scheduler because I'm not entirely sure we need one for this. The place it would be useful is if there are long delays where a system restart may happen in the middle, but beyond that I don't think a job scheduler adds much benefit. Again I'm open to hearing other opinions.
> Handle offsets in the reporting workflow

- src/services/messaging.js
- src/utils/actions.js
- src/utils/fhir.js
Forward message response (either from an async post to $process-message or the sync response from submitting the bundle) to the EHR server.
> Forward message response to EHR

- src/app.js
- src/routes/servers.js
- src/routes/subscriptions.js
- src/utils/fhir.js
- src/utils/reporting_workflow.js
On startup subscribe to PlanDefinition on all KA repos. Implement the subscription notification endpoints to store the updated artifacts on change.
HAPI won't let me subscribe to criteria `PlanDefinition` so I opted for `PlanDefinition?_lastUpdated=gt2021-01-01`. If anyone knows a better way to subscribe to all PlanDefinitions without requiring the R5 backport topics let me know.
> Knowledge Artifact Subscriptions

- src/utils/fhir.js
Currently this is branched off of Ben's PR #19 to incorporate the subscription changes there.
When the PlanDefinitions from KA are refreshed, subscriptions are saved to the database and created on the EHR server.
- Call `subscriptionsFromBundle` whenever PlanDefinitions are refreshed.
- Added an id to subscription resources that is `${planDef.id}${namedEventCoding.code}` so that they can be updated in the database.
- Using `axios.put` so that the EHR server uses this `id` so it will know when to create/update.
- Added a regex in `generateSubscription` to check if `criteria` has at least one search param since HAPI is expecting this(mentioned in #19).
- If `criteria` doesn't have a search param, I add `?_lastUpdated=gt2021-01-01` to it so we can post to EHR server. If we come to a …
> Subscription setup

- bin/www
- src/app.js
- src/routes/servers.js
- src/routes/subscriptions.js
- src/services/messaging.js
- src/storage/collections.js
- src/storage/logs.js
- src/utils/actions.js
- src/utils/client.js
- src/utils/fhir.js
- src/utils/reporting_workflow.js
Adds a middleware for requests, puts resources into collections based on resourceType (this was how it was being done already), and puts debug messages into the database.  The database log just adds on a timestamp and location to the message, and the files define their own location when they import the debug function.
> add logs to db

- webpack.config.js
Webpack config was missing a line, missed it when it was originally pulled in because of the way things were set up.  There were no errors with `App.jsx`, I think this is because `index.jsx` is the entry point and imports it, so it wasn't caught in the original pull request.
This should allow importing of js files.  Right now webpack isn't considering js files in the path valid modules to load, this will solve that problem.  If you want to test, just copy the missing line into your own webpack config file if its experiencing errors or checkout this branch and create some example directories and `.jsx` files to import.
> resolve js files

- package.json
- src/app.js
- src/handlers/crudHandler.js
- src/routes/subscriptions.js
- src/services/messaging.js
- src/utils/actions.js
- src/utils/auth.js
- src/utils/fhir.js
- src/utils/reporting_workflow.js
Replace all uses of insert/upsert/select for FHIR resources which use id to instead use fullUrl. This required a little refactoring, most notably changing subscription notifications to include the fullUrl. I did not update non-fhir collections such as servers.
I did some testing but since this touches a lot of different pieces looking for some help to make sure I didn't accidentally break anything.
> Use fullUrl to access resources in DB

- package-lock.json
- src/routes/subscriptions.js
- src/services/subscriptions.js
- src/utils/fhir.js
Update notification endpoints to accept R5 Backport Subscriptions which come as a Bundle. Still unclear as to whether or not the PUT `{base url}/{resourceType}/{resourceId}` is used in the backport subscriptions
> Receive R5 Subscriptions

- src/ui/components/Collections/Collections.jsx
- src/ui/components/Collections/SortedTableHead.jsx
- src/ui/components/Collections/styles.jsx
- src/ui/components/Dashboard/styles.jsx
- src/ui/components/styles/theme.jsx
The collections now are displayed in a table as shown in the designs.  The pagination works and you can sort the columns, but none of the buttons are functional.  The only differences from the design are some minor color/font and spacing issues and the "Add server" button being replaced with a generic "Add new" button.  This button could be changed to use the actual collections name, but we'd have to do a bit of extra processing.  
Different collections can be given different parameters as well, the "Add new" button won't show up for "Logs" and "Requests".
> add table ui

- .env.dev
- README.md
- src/__tests__/app.test.js
- src/utils/auth.js
Replaces the hardcoded admin token with an env variable. To test set `ADMIN_TOKEN` env var to a value and then verify you can use that to access `{base url}/index`.
> Use env var for admin token

- package-lock.json
- package.json
- src/services/test_service.js
- src/storage/collections.js
- src/storage/logs.js
- src/ui/components/Dashboard/DashboardLayout.jsx
- src/ui/components/Dashboard/NavBar.jsx
- src/ui/components/Dashboard/styles.jsx
- src/ui/components/Notifications/Notifications.jsx
- src/ui/components/Notifications/index.js
- src/ui/components/Notifications/styles.jsx
- src/ui/components/styles/theme.jsx
Adds the UI for the notification tab, functionality for the notification bell icon, and a new collection to the database specifically for notifications under the assumption that future notifications won't all exclusively be errors.  The notification data structure should also include the userId if it can, but I've left that out for now to simplify things.
To test the UI, you can either trigger an error (that reports using the `error()` log function) or you can just visit `/index`, since I've added some testing code to create an error when visiting the test endpoint.  This should trigger the backend UI to display the new notification, which can be dismissed by pressing on the grey checkmark.
> Notifications

- src/handlers/crudHandler.js
- src/routes/wellknown.js
- src/utils/auth.js
- Check access token scope before authorizing request
- Added `system/*.*` and `system/*.write` scopes in addition to `system/*.read`
- All requests are allowed when scope includes `system/*.*`
- GET requests are allowed when scope includes `system/*.read`
- POST, PUT, and DELETE requests are allowed when scope includes `system/*.write`
- To test, you must first get an access token from the keycloak server. I added another client with the client_id `test` which made scopes optional. client_secret can be found on the keycloak server.
- You should get a 401 with an "Insufficient scope" message if you don't have the correct scope.
> Check Access Token Scope

- src/ui/.eslintrc.json
- src/ui/components/Admin/Admin.jsx
- src/ui/components/Auth/Login.jsx
- src/ui/components/Auth/auth.css
- src/ui/components/Auth/styles.jsx
- src/ui/components/styles/theme.jsx
changes the login page to have a simple UI.  The forget password and keep my logged in options don't do anything for now.  But you can press enter to log in after putting in credentials now.
In order to get the linter to work, I had to add an extra `eslintrc` file so that the UI files would allows global browser variables like `document`.  
You can test the changes by running the app and going to the home page to log in.
> login page ui

- docker-compose.yml
- docker/aws-docker-compose.yml
- src/ui/components/Collections/Collections.jsx
- src/utils/actions.js
- src/utils/client.js
- src/utils/fhir.js
Three fixes to get it working on AWS:
1. Include the clientId for servers in the UI. If this field is not included when creating the server the authorization will fail. I know we are removing auth for the connectathon but this won't break anything without auth (it will just be extra info there which means nothing).
2. Update the docker-compose files to include the DEBUG and ADMIN_TOKEN environment variables
3. Ensures errors are logged with a helpful message and id
> Small Fixes for Running on AWS

- src/ui/components/Collections/Collections.jsx
- src/utils/client.js
- src/utils/fhir.js
This PR brings in a few fixes based on testing against the Epic and Cerner sandboxes:
- Cerner doesn't support wildcard scopes, so now we can configure a custom set of scopes to use per server
- Cerner uses the `client_secret_basic` method of authentication which uses a client_secret instead of a JWT
- Epic's smart-configuration isn't at `{baseUrl}/.well-known/smart-configuration` so if getting that URL fails, we can try to get the token endpoint via the server metadata
- Posting Subscriptions to the subscription-proxy fails if we don't specify the content-type
> Fixes based on sandbox testing

- .env.dev
- README.md
- docker-compose.yml
- docker/aws-docker-compose.yml
- src/utils/auth.js
- src/utils/client.js
- Added `REQUIRE_AUTH` and `REQUIRE_AUTH_FOR_OUTGOING` environment variables.
- If set to `false`, the app will authorize all requests and not retrieve access tokens for outgoing requests.
> Add env variables to remove auth

- src/utils/actions.js
- src/utils/reporting_workflow.js
Fetches resources as specified by the `PlanDefinition.action.input` field on the `create-report` action. Note that this should work when the trigger is a Patient or an Encounter, not sure about other resource types such as Condition yet. 
I used the attached encounter resource, pointing to all our internal FHIR servers, for testing:
[mitre_sample_enc.json.txt](https://github.com/mcode/medmorph-backend/files/6462135/mitre_sample_enc.json.txt)
> Fetch resources in create-report action

- package-lock.json
- package.json
- src/services/subscriptions.js
- src/storage/collections.js
- src/utils/__tests__/actions.test.js
- src/utils/actions.js
- src/utils/fhir.js
- src/utils/knowledgeartifacts.js
- src/utils/valueSetUtils.js
A joint effort with @danlee1025.
This PR adds support for querying and filtering resources by valueset, and plugging them into fhirpath expressions, for use in the `check-trigger-codes` action.
Two sample resources for testing (based on patients in the internal pathways.mitre.org EHR):
- an encounter for a patient that has a condition with code "408643008", so this encounter should match the trigger codes and proceed with reporting [mitre_sample_enc_match.json.txt](https://github.com/mcode/medmorph-backend/files/6473693/mitre_sample_enc_match.json.txt)
- an encounter for a patient that has no conditions in the valueset, so this encounter should not match the trigger codes, and the reporting workflow should stop [mitre_sample_enc_no_match.json.txt](https://github.com/mcode/medmorph-backend/ …
> Support variables in fhirpath using inputs

- src/routes/index.js
When the refreshAllKnowledgeArtifacts function was moved from `utils/fhir` to `utils/knowledgeartifact` the import in `index.js` was not updated. I'm not sure why this wasn't caught by lint etc, but this fix allows that route to work again.
> Fix fetch-ka bug

- README.md
- package-lock.json
- package.json
- src/handlers/crudHandler.js
- src/routes/index.js
- src/services/messaging.js
- src/services/subscriptions.js
- src/storage/logs.js
- src/storage/servers.js
- src/utils/actions.js
- src/utils/client.js
- src/utils/fhir.js
- src/utils/knowledgeartifacts.js
- src/utils/reporting_workflow.js
- src/utils/subscriptions.js
- src/utils/url.js
This introduces the `normalizeUrl` library to the backend.  Any instance of URLs being compared has been replaced with the `compareUrls` function which normalizes the urls before they're compared.  This should ensure consistency.  The normalize function does produce an error when it's fed a bad URL, and I was considering adding a try/catch, but there shouldn't be a situation (outside of the `storeRequests` function) where it's fed a bad url.
> normalize urls when compared

- config.js
- src/storage/configUtil.js
- src/storage/servers.js
- src/utils/client.js
- src/utils/fhir.js
- src/utils/knowledgeartifacts.js
Attempt to register the client with the PHA using [OAuth 2.0 Dynamic Client Registration Spec](https://datatracker.ietf.org/doc/html/rfc7591). 
One big note about this: the spec is pretty loose on the client metadata. Keycloak only support OpenID which further restricts the OAuth 2.0 spec and does not work for the `client_credentials` grant flow required for SMART Backend Authorization. I set up an Okta authorization server to test this but:
1. It requires an extra metadata not defined in the spec called `application_type`. This must be set to `service` for the client to be registered as defined in the SMART Backend Auth spec. This extra information should not break anything else so I left it in there for now.
2. It does not support `jwks_uri`, only `jwks`. The SMART Backend Auth spec …
> Dynamic client registration

- docker/mitre-docker-compose.yml
The CD on pathways.mitre.org for the backend does not work because the docker-compose file has the baseurl set to localhost. This adds a new docker-compose file with updated env like the aws one in the same directory. This file is identical to the `src/docker-compose.yml` except for changing `localhost` to `pathways.mitre.org`
> Add mitre docker-compose file
